repos:
  - repo: local
    hooks:
      - id: black
        name: black (local)
        entry: black
        language: system
        types: [python]
        args: ["--line-length=88"]

      - id: isort
        name: isort (local)
        entry: isort
        language: system
        types: [python]

      - id: husky
        name: run husky pre-commit
        entry: npx husky run pre-commit
        language: system
