files.extend-exclude = [
    "cvat-ui/src/assets/opencv_4.8.0.js",
    "cvat-data/src/ts/3rdparty/*.js",
    "site/themes/docsy/",
    "*.log",
    "*.min.js",
    "*.patch",
]
default.extend-ignore-re = [
    # test passwords
    "\"md5.*?\"",

    # Line ignore with trailing "# spellchecker:disable-line"
    # or trailing "// spellchecker:disable-line"
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",

    # Line block with "# spellchecker:<on|off>"
    # or "// spellchecker:<on|off>"
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on"
    # Taken from https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations

]

[default.extend-words]
AVOD = "AVOD"
NAM = "NAM"
blok = "block"
cheeck = "check"
configurate = "configure"
convertation = "conversion"
convertor = "converter"
cubiod = "cuboid"
cuboiud = "cuboid"
cuccessfully = "successfully"
firts = "first"
leafs = "leafs"
nd = "nd"
onject = ""
perameters = "parameters"
segway = "segway"
splitted = "splitted"
succefull = "successful"
tesk = "task"
tpic = "tpic"
trak = "trak"
typ = "type"
