version: '3.3'

services:
  cvat_ci:
    image: cvat_ci
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - cvat
      - cvat_ui
      - cvat_proxy
    environment:
      COVERALLS_REPO_TOKEN:
      TRAVIS:
      TRAVIS_JOB_ID:
      TRAVIS_BRANCH:
      TRAVIS_PULL_REQUEST:
      CONTAINER_COVERAGE_DATA_DIR:
    volumes:
      - ${HOST_COVERAGE_DATA_DIR}:${CONTAINER_COVERAGE_DATA_DIR}
