# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  datawiza_access_broker:
    image: registry.gitlab.com/datawiza/access-broker
    container_name: datawiza-access-broker
    ports:
      - "443:443"
    restart: always
    environment:
      # To obtain a valid provisioning key-secret pair, please
      # visit https://console.datawiza.com/
      # And follow the step-by-step instruction in
      # https://docs.datawiza.com/guides/cvat.html
      PROVISIONING_KEY: ${YOUR_PROVISIONING_KEY}
      PROVISIONING_SECRET: ${YOUR_PROVISIONING_SECRET}
    networks:
      - cvat

  cvat_server:
    environment:
      HEADER_AUTH_ENABLE: 'true'

  traefik:
    ports:
      - 8090:8090
