additionalProperties:
  projectName: "cvat_sdk"
  packageUrl: "https://github.com/cvat-ai/cvat"
  packageName: "cvat_sdk.api_client"
  initRequiredVars: true
  generateSourceCodeOnly: false
  generatorLanguageVersion: '>=3.8'
globalProperties:
  generateAliasAsModel: true
  apiTests: false
  modelTests: false
files:
  api_summary.mustache:
    destinationFilename: api_summary.md
