version: '3.3'

services:
  cvat_db:
    container_name: reb_cvat_db
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - reb_cvat_db:/var/lib/postgresql/data
    networks:
      reb_cvat:
        aliases:
          - postgres
    ports:
      - 5432:5432

  cvat_redis:
    container_name: reb_cvat_redis
    image: redis:4.0-alpine
    restart: unless-stopped
    networks:
      reb_cvat:
        aliases:
          - redis

  cvat_server:
    container_name: reb_cvat
    image: retechlabs/rebotics-cvat:${VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
      - cvat_minio
    env_file:
      # create this if it does not exist, based on example
      .env.local
    environment:
      no_proxy: 'elasticsearch,kibana,logstash,nuclio,opa,${no_proxy}'
    volumes:
      - reb_cvat_data:/home/django/data
    ports:
      - "8080:8080"
    networks:
      - reb_cvat
      - reboticsadmin_default

  cvat_opa:
    container_name: reb_cvat_opa
    image: retechlabs/rebotics-cvat-opa:${VERSION:-latest}
    restart: unless-stopped
    networks:
      reb_cvat:
        aliases:
          - opa

  cvat_minio:
    container_name: reb_cvat_minio
    image: minio/minio:latest
    restart: unless-stopped
    entrypoint: sh
    command: -c 'mkdir -p /data/demo-bucket && minio server /data --address 0.0.0.0:9007'
    environment:
      MINIO_ROOT_USER: 'minio_admin'
      MINIO_ROOT_PASSWORD: 'minio_admin'
    volumes:
      - ../.s3:/data
    networks:
      reb_cvat:
        aliases:
          - minio
    ports:
      - 9007:9007

volumes:
  reb_cvat_db:
  reb_cvat_data:

networks:
  reb_cvat:
  reboticsadmin_default:
    external: true
