name: ESLint
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16.x'
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Run checks
        env:
          PR_FILES_AM: ${{ steps.files.outputs.added_modified }}
          PR_FILES_RENAMED: ${{ steps.files.outputs.renamed }}
        run: |
          PR_FILES="$PR_FILES_AM $PR_FILES_RENAMED"
          for FILE in $PR_FILES; do
              EXTENSION="${FILE##*.}"
              if [[ $EXTENSION == 'js' || $EXTENSION == 'ts' || $EXTENSION == 'jsx' || $EXTENSION == 'tsx' ]]; then
                  CHANGED_FILES+=" $FILE"
              fi
          done

          if [[ ! -z $CHANGED_FILES ]]; then
            yarn install --frozen-lockfile && cd tests && yarn install --frozen-lockfile && cd ..
            yarn add eslint-detailed-reporter -D -W
            mkdir -p eslint_report

            echo "ESLint version: "$(npx eslint --version)
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            npx eslint $CHANGED_FILES -f node_modules/eslint-detailed-reporter/lib/detailed.js -o ./eslint_report/eslint_checks.html
          else
            echo "No files with the \"js|ts|jsx|tsx\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report
          path: eslint_report
