name: Pylint
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Run checks
        env:
          PR_FILES_AM: ${{ steps.files.outputs.added_modified }}
          PR_FILES_RENAMED: ${{ steps.files.outputs.renamed }}
        run: |
          PR_FILES="$PR_FILES_AM $PR_FILES_RENAMED"
          for FILE in $PR_FILES; do
              EXTENSION="${FILE##*.}"
              if [[ "$EXTENSION" == 'py' ]]; then
                  CHANGED_FILES+=" $FILE"
              fi
          done

          if [[ ! -z $CHANGED_FILES ]]; then
            sudo apt-get --no-install-recommends install -y build-essential curl python3-dev python3-pip python3-venv
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip wheel setuptools
            pip install pylint-json2html
            pip install $(egrep "pylint.*==.*" ./cvat/requirements/development.txt)
            pip install $(egrep "django==.*" ./cvat/requirements/base.txt)
            mkdir -p pylint_report

            echo "Pylint version: "$(pylint --version | head -1)
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            pylint $CHANGED_FILES --output-format=json > ./pylint_report/pylint_checks.json || EXIT_CODE=$(echo $?) || true
            pylint-json2html -o ./pylint_report/pylint_checks.html ./pylint_report/pylint_checks.json
            deactivate
            exit $EXIT_CODE
          else
            echo "No files with the \"py\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: pylint_report
          path: pylint_report
