name: Linter
on: pull_request
jobs:
  Remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 12

      - name: Run checks
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          PR_FILES=$(curl -s -X GET -G $URL | jq -r '.[] | select(.status != "removed") | .filename')
          for files in $PR_FILES; do
            extension="${files##*.}"
            if [[ $extension == 'md' ]]; then
              changed_files_remark+=" ${files}"
            fi
          done

          if [[ ! -z ${changed_files_remark} ]]; then
            npm ci
            npm install remark-cli vfile-reporter-json
            mkdir -p remark_report

            echo "Remark version: "`npx remark --version`
            echo "The files will be checked: "`echo ${changed_files_remark}`
            npx remark --quiet --report json --no-stdout ${changed_files_remark} 2> ./remark_report/remark_report.json
            get_report=`cat ./remark_report/remark_report.json  | jq -r '.[] | select(.messages | length > 0)'`
             if [[ ! -z ${get_report} ]]; then
              pip install json2html
              python ./tests/json_to_html.py ./remark_report/remark_report.json
              exit 1
            fi
          else
            echo "No files with the \"md\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: remark_report
          path: remark_report
